### ISSUE TITLE
Si on execute la commande "nwayo" dans un dossier de projet qui n'a pas encore eu un "npm install"

### ISSUE THREAD

**Issue by benoitrenaud** [absolunet/nwayo-cli#9]
throw err;
    ^

Error: Cannot find module '/PROJECT_PATH/nwayo/node_modules/@absolunet/nwayo-workflow/cli'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at module.exports (/usr/local/lib/node_modules/@absolunet/nwayo-cli/index.js:38:4)
    at Object.<anonymous> (/usr/local/lib/node_modules/@absolunet/nwayo-cli/bin/nwayo:4:20)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)

**Comment by jblandry** [comment]
Done via ff8cc094c84256079fdd8a60f928d05ec59cc8a3
